# Generated by Django 3.0.8 on 2020-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.AddField(
            model_name='index',
            name='category',
            field=models.CharField(choices=[('stocks', 'stocks'), ('commodities', 'commodities'), ('currencies', 'currencies')], default='stock', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(choices=[('AAPL', 'apple'), ('btc', 'btc')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('twelvedata', 'twelvedata')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('name', 'url')},
        ),
    ]
