# Generated by Django 3.0.8 on 2020-07-05 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='from_timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 7, 5, 12, 22, 33, 195379)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('twelvedata', 'twelvedata')], max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
    ]
